In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('insurance_data.csv')
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
df.shape

(28, 3)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(['bought_insurance'], axis='columns'), df.bought_insurance, test_size=0.2, random_state = 25)

In [5]:
#Preprocessing
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

In [6]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss= 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(X_train_scaled, y_train, epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 9ms/step - loss: 0.5584 - accuracy: 0.6818
Epoch 1874/5000
1/1 [==============================] - 0s 7ms/step - loss: 0.5584 - accuracy: 0.6818
Epoch 1875/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5584 - accuracy: 0.6818
Epoch 1876/5000
1/1 [==============================] - 0s 8ms/step - loss: 0.5583 - accuracy: 0.6818
Epoch 1877/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5583 - accuracy: 0.6818
Epoch 1878/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5582 - accuracy: 0.6818
Epoch 1879/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.5582 - accuracy: 0.6818
Epoch 1880/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.5581 - accuracy: 0.6818
Epoch 1881/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.5581 - accuracy: 0.6818
Epoch 1882/5000
1/1 [==============================

In [7]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 258ms/step - loss: 0.3550 - accuracy: 1.0000


[0.3549776077270508, 1.0]

In [8]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 118ms/step


array([[0.7054848 ],
       [0.3556957 ],
       [0.16827832],
       [0.47801185],
       [0.7260696 ],
       [0.8294983 ]], dtype=float32)

In [9]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [10]:
coef , intercept = model.get_weights()

In [11]:
coef, intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

In [12]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))

sigmoid(18)

0.9999999847700205

In [13]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [14]:
X_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [15]:
def prediction_function(age, affordibility):
  net_input = coef[0]*age + coef[1]*affordibility + intercept
  return sigmoid(net_input)

prediction_function(0.47, 1)

0.705484819775958

In [16]:
prediction_function(0.18, 1)

0.35569571637887243